name: CLDF-validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest-cldf
    - name: Test with pytest
      run: |
        pytest --cldf-metadata=cldf/lexicon-metadata.json test.py
        pytest --cldf-metadata=cldf/phonemes-metadata.json test.py
        pytest --cldf-metadata=cldf/phonology-metadata.json test.py
        pytest --cldf-metadata=cldf/wordlist-metadata.json test.py
